#spring.application.name=Mongo-Demo

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring

  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
